# Step 1 : Build the Angular's application
FROM node:22-alpine AS build
WORKDIR /app

# Copy the configuration's files for dependencies
COPY package*.json ./

# Copy the remaining source code
COPY . .

# Make a clean installation for the dependencies (using the lock file)
RUN npm ci

# Build the application in production mode
RUN npm run build -- --configuration=production

# Step 2 : Web server for the production (Nginx)
FROM nginx:alpine

# Copy all the configuration for Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy all files built from last step
# Note: Angular 18 often placed some files in dist/project-name/browser
COPY --from=build /app/dist/employee-management-app/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
