server {
  listen 80;
  server_name localhost;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    # Try to serve the file, otherwise redirect through index.html
    try_files $uri $uri/ /index.html;
  }

  # Control cache for the statics assets
  location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
    expires 30d;
    add_header Cache-Control "public";
  }
}
